### ISSUE TITLE
Exception - Call to a member function get() on null

### ISSUE THREAD

**Issue by jb-fol** [synergylearning/moodle-local_wikiexport#5]
Can't access "Permissions" or "Locally Assigned Roles" option in Wiki administration on 3.9 or 3.10

Error: Exception - Call to a member function get() on null

Debug info: 
Error code: generalexceptionmessage
Stack trace:
line 607 of /local/wikiexport/lib.php: Error thrown
line 1527 of /lib/navigationlib.php: call to local_wikiexport_extend_navigation()
line 1490 of /lib/navigationlib.php: call to global_navigation->load_local_plugin_navigation()
line 4145 of /lib/navigationlib.php: call to global_navigation->initialise()
line 768 of /lib/pagelib.php: call to settings_navigation->__construct()
line 830 of /lib/pagelib.php: call to moodle_page->magic_get_settingsnav()
line 111 of /blocks/admin_bookmarks/block_admin_bookmarks.php: call to moodle_page->__get()
line 341 of /blocks/moodleblock.class.php: call to block_admin_bookmarks->get_content()
line 235 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1181 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1239 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 374 of /lib/blocklib.php: call to block_manager->ensure_content_created()
line 3953 of /lib/outputrenderers.php: call to block_manager->region_has_content()
line 40 of /theme/boost/layout/columns2.php: call to core_renderer->blocks()
line 1374 of /lib/outputrenderers.php: call to include()
line 1304 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 1950 of /lib/setuplib.php: call to core_renderer->header()
line 206 of /admin/roles/permissions.php: call to bootstrap_renderer->__call()

I know the plugin is not supported past 3.1 at the moment though - but seems to work well on later versions apart from this error.

**Comment by davosmith** [comment]
Hi Jon,

I've pushed a fix that I think will sort out the problem (but I've not tested it at all) - can you check if this now works?

Davo

**Comment by jb-fol** [comment]
Perfect, that works :)
Thanks Davo

**Comment by davosmith** [comment]
I'll close this ticket then - I'm not regularly publishing updates to the Moodle plugins directory for this one, but the fixed version is here, if anyone needs it.
